-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- Link to schema: https://app.quickdatabasediagrams.com/#/d/uZAh4j
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.

-- Modify this code to update the DB schema diagram.
-- To reset the sample schema, replace everything with
-- two dots ('..' - without quotes).

CREATE TABLE "AIRPORT_COORDINATES" (
    "ORIGIN_AIRPORT_ID" INT   NOT NULL,
    "DISPLAY_AIRPORT_NAME" VARCHAR   NOT NULL,
    "LATITUDE" FLOAT   NOT NULL,
    "LONGITUDE" FLOAT   NOT NULL,
    CONSTRAINT "pk_AIRPORT_COORDINATES" PRIMARY KEY (
        "ORIGIN_AIRPORT_ID"
     )
);

CREATE TABLE "CARRIER_DECODE" (
    "AIRLINE_ID" INT   NOT NULL,
    "OP_UNIQUE_CARRIER" VARCHAR   NOT NULL,
    "CARRIER_NAME" VARCHAR   NOT NULL
);

CREATE TABLE "ONTIME_REPORTING" (
    "MONTH" INT   NOT NULL,
    "DAY_OF_MONTH" VARCHAR   NOT NULL,
    "DAY_OF_WEEK" INT   NOT NULL,
    "OP_UNIQUE_CARRIER" VARCHAR   NOT NULL,
    "TAIL_NUM" VARCHAR   NOT NULL,
    "OP_CARRIER_FL_NUM" INT   NOT NULL,
    "ORIGIN_AIRPORT_ID" INT   NOT NULL,
    "ORIGIN" VARCHAR   NOT NULL,
    "ORIGIN_CITY_NAME" VARCHAR   NOT NULL,
    "DEST_AIRPORT_ID" INT   NOT NULL,
    "DEST" VARCHAR   NOT NULL,
    "DEST_CITY_NAME" VARCHAR   NOT NULL,
    "CRS_DEP_TIME" INT   NOT NULL,
    "DEP_TIME" VARCHAR   NOT NULL,
    "DEP_DELAY_NEW" FLOAT   NOT NULL,
    "DEP_DEL15" FLOAT   NOT NULL,
    "DEP_TIME_BLK" VARCHAR   NOT NULL,
    "CRS_ARR_TIME" INT   NOT NULL,
    "ARR_TIME" INT   NOT NULL,
    "ARR_DELAY_NEW" INT   NOT NULL,
    "ARR_TIME_BLK" VARCHAR   NOT NULL,
    "CANCELLED" BOOLEAN   NOT NULL,
    "CANCELLATION_CODE" VARCHAR   NOT NULL,
    "CRS_ELAPSED_TIME" INT   NOT NULL,
    "ACTUAL_ELAPSED_TIME" INT   NOT NULL,
    "DISTANCE" INT   NOT NULL,
    "DISTANCE_GROUP" INT   NOT NULL,
    "CARRIER_DELAY" INT   NOT NULL,
    "WEATHER_DELAY" INT   NOT NULL,
    "NAS_DELAY" INT   NOT NULL,
    "SECURITY_DELAY" INT   NOT NULL,
    "LATE_AIRCRAFT_DELAY" INT   NOT NULL
);

CREATE TABLE "P10_EMPLOYEES" (
    "YEAR" INT   NOT NULL,
    "AIRLINE_ID" INT   NOT NULL,
    "OP_UNIQUE_CARRIER" VARCHAR   NOT NULL,
    "UNIQUE_CARRIER_NAME" VARCHAR   NOT NULL,
    "CARRIER" VARCHAR   NOT NULL,
    "CARRIER_NAME" VARCHAR   NOT NULL,
    "ENTITY" VARCHAR   NOT NULL,
    "GENERAL_MANAGE" INT   NOT NULL,
    "PILOTS_COPILOTS" INT   NOT NULL,
    "OTHER_FLT_PEERS" INT   NOT NULL,
    "PASS_GEN_SVC_ADMIN" INT   NOT NULL,
    "MAINTENANCE" INT   NOT NULL,
    "ARCFT_TRAF_HANDLING_GRP1" INT   NOT NULL,
    "GEN_ARCFT_TRAF_HANDLING" INT   NOT NULL,
    "AIRCRAFT_CONTROL" INT   NOT NULL,
    "PASSENGER_HANDLING" INT   NOT NULL,
    "CARGO_HANDLING" INT   NOT NULL,
    "TRAINEES_INTRUCTOR" INT   NOT NULL,
    "STATISTICAL" INT   NOT NULL,
    "TRAFFIC_SOLICITERS" INT   NOT NULL,
    "OTHER" INT   NOT NULL,
    "TRANSPORT_RELATED" INT   NOT NULL,
    "TOTAL" INT   NOT NULL
);

CREATE TABLE "T3_AIR_CARRIER_SUMMARY_AIRPORT_ACTIVITY" (
    "OP_UNIQUE_CARRIER" VARCHAR   NOT NULL,
    "CARRIER_NAME" VARCHAR   NOT NULL,
    "ORIGIN_AIRPORT_ID" INT   NOT NULL,
    "SERVICE_CLASS" VARCHAR   NOT NULL,
    "REV_ARCRFT_DEP_PERF_510" INT   NOT NULL,
    "REV_PAX_ENP_110" INT   NOT NULL
);

CREATE TABLE "AIRPORT_WEATHER" (
    "STATION" VARCHAR   NOT NULL,
    "NAME" VARCHAR   NOT NULL,
    "DATE" DATE   NOT NULL,
    "AWND" FLOAT   NOT NULL,
    "PGTM" FLOAT   NOT NULL,
    "PRCP" FLOAT   NOT NULL,
    "PSUN" INT   NOT NULL,
    "SN32" INT   NOT NULL,
    "SNOW" FLOAT   NOT NULL,
    "SNWD" FLOAT   NOT NULL,
    "SX32" INT   NOT NULL,
    "TAVG" FLOAT   NOT NULL,
    "TMAX" FLOAT   NOT NULL,
    "TMIN" FLOAT   NOT NULL,
    "TSUN" INT   NOT NULL,
    "WDF2" FLOAT   NOT NULL,
    "WDF5" FLOAT   NOT NULL,
    "WESD" BOOLEAN   NOT NULL,
    "WSF2" FLOAT   NOT NULL,
    "WSF5" FLOAT   NOT NULL,
    "WT01" BOOLEAN   NOT NULL,
    "WT02" BOOLEAN   NOT NULL,
    "WT03" BOOLEAN   NOT NULL,
    "WT04" BOOLEAN   NOT NULL,
    "WT05" BOOLEAN   NOT NULL,
    "WT06" BOOLEAN   NOT NULL,
    "WT07" BOOLEAN   NOT NULL,
    "WT08" BOOLEAN   NOT NULL,
    "WT09" BOOLEAN   NOT NULL,
    "WT10" BOOLEAN   NOT NULL,
    "WT18" BOOLEAN   NOT NULL,
    "TOBS" INT   NOT NULL,
    "WT11" BOOLEAN   NOT NULL
);

CREATE TABLE "AIRPORTS_LIST" (
    "ORIGIN_AIRPORT_ID" INT   NOT NULL,
    "DISPLAY_AIRPORT_NAME" VARCHAR   NOT NULL,
    "ORIGIN_CITY_NAME" VARCHAR   NOT NULL,
    "NAME" VARCHAR   NOT NULL
);

CREATE TABLE "B43_AIRCRAFT_INVENTORY" (
    "MANUFACTURE_YEAR" INT   NOT NULL,
    "TAIL_NUM" VARCHAR   NOT NULL,
    "NUMBER_OF_SEATS" INT   NOT NULL
);

ALTER TABLE "AIRPORT_COORDINATES" ADD CONSTRAINT "fk_AIRPORT_COORDINATES_ORIGIN_AIRPORT_ID_ORIGIN_AIRPORT_ID" FOREIGN KEY("ORIGIN_AIRPORT_ID", "ORIGIN_AIRPORT_ID")
REFERENCES "ONTIME_REPORTING" ("ORIGIN_AIRPORT_ID", "DEST_AIRPORT_ID");

ALTER TABLE "CARRIER_DECODE" ADD CONSTRAINT "fk_CARRIER_DECODE_AIRLINE_ID_OP_UNIQUE_CARRIER_CARRIER_NAME" FOREIGN KEY("AIRLINE_ID", "OP_UNIQUE_CARRIER", "CARRIER_NAME")
REFERENCES "P10_EMPLOYEES" ("AIRLINE_ID", "OP_UNIQUE_CARRIER", "CARRIER_NAME");

ALTER TABLE "AIRPORTS_LIST" ADD CONSTRAINT "fk_AIRPORTS_LIST_ORIGIN_CITY_NAME" FOREIGN KEY("ORIGIN_CITY_NAME")
REFERENCES "ONTIME_REPORTING" ("ORIGIN_CITY_NAME");

ALTER TABLE "AIRPORTS_LIST" ADD CONSTRAINT "fk_AIRPORTS_LIST_NAME" FOREIGN KEY("NAME")
REFERENCES "AIRPORT_WEATHER" ("NAME");

ALTER TABLE "B43_AIRCRAFT_INVENTORY" ADD CONSTRAINT "fk_B43_AIRCRAFT_INVENTORY_TAIL_NUM" FOREIGN KEY("TAIL_NUM")
REFERENCES "ONTIME_REPORTING" ("TAIL_NUM");

